### ISSUE TITLE
Can't see what what I'm typing while creating a Group

### ISSUE THREAD

**Issue by Galthariel** [ChrisKader/LFMPlus#8] opened 2021-11-22 02:25 UTC
The difference between both screenshots is that when I can see what I'm typing there is a description saying "A descriptive title for your group listing" and when I can't see what I'm typing there is nothing there. I can still type and list but can't see what I'm typing...

https://ibb.co/F432StR

https://ibb.co/vxCHdwJ

Last but not least BugSack doesn't show any errors and the issue happens randomly (not always). With the addon disabled never happens

**Comment by ChrisKader** [comment] 2021-11-22 02:37
What addon are you using to skin your UI?

**Comment by Galthariel** [comment] 2021-11-22 02:54
I use Skinner for a few years now

**Comment by ChrisKader** [comment] 2021-11-25 00:01
Do you have an authenticator on your account?

**Comment by ChrisKader** [comment] 2021-11-25 00:46
I am unable to replicate the issue on my end (even with nothing but skinner and LFM+ installed.) However, I expect this is due to how the skinning addon is setting text/transparency for some UI elements and no directly related to LFM+. I am going to close this issue for now. If you are able to provide steps to reproduce the issue reliably, please re-open this issue.

**Closed by ChrisKader** 2021-11-25 00:46 UTC

**Comment by Galthariel** [comment] 2021-11-25 01:24
Yes, I do use/have an Authenticator and no worries about the issue. :-)
